version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sls_policy_gen
    volumes:
      - ./:/go/src/github.com/highhi/sls-policy-gen
    tty: true
  