version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: slspolicygen
    volumes:
      - ./:/go/src/github.com/highhi/slspolicygen
    tty: true
  